app/main/__init__.py
"""
Main Blueprint:
This blueprint contains routes and views for the main functionality of the application

Keyword arguments:
argument -- N/A
Return:
	main blueprint: The Blueprint object for main functionality.
"""

from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates')

from . import views, forms

app/main/views.py
from . import main
from flask import (
    render_template,
    session,
    redirect,
    url_for,
    flash,
    request,
    current_app,
    send_from_directory,
)
from flask_babel import _, refresh
from werkzeug.exceptions import ServiceUnavailable
import os


@main.route("/")
@main.route("/index")
def index():
    """
    Renders the index.html template.

    Returns:
        The rendered index.html template.
    """
    return render_template("index.html")


@main.route("/change-language", methods=["GET", "POST"])
def language():
    """
    Handles the language change request.

    If the request method is POST, it changes the selected language in the session.
    If the selected language is recognized, it flashes a success message and redirects to the index page.
    If the selected language is not recognized, it flashes an error message and redirects to the index page.

    Returns:
        If the request method is GET, the rendered change_language.html template.
        If the request method is POST and the selected language is recognized, a redirect to the index page.
        If the request method is POST and the selected language is not recognized, a redirect to the index page.
    """
    if request.method == "POST":
        selected_language = request.form.get("languages")
        session["language"] = selected_language
        if selected_language in current_app.config["LANGUAGES"]:
            flash(
                "Language changed to "
                + current_app.config["LANGUAGES"].get(selected_language),
                "success",
            )
            refresh()
            return redirect(url_for("main.index"))
        flash(_("Language not recognized."), "error")
        return redirect(url_for("main.index"))
    return render_template("change_language.html")


@main.route("/about")
def about():
    """
    Renders the about.html template.

    Returns:
        The rendered about.html template.
    """
    return render_template("about.html")


@main.route("/service_unavailable")
def service_unavailable():
    """
    Renders the 503.html template with a 503 status code.

    Returns:
        The rendered 503.html template with a 503 status code.
    """
    try:
        raise ServiceUnavailable("Service is temporarily unavailable.")
    except ServiceUnavailable as e:
        return render_template("503.html"), 503


@main.route("/nonexistent_route")
def nonexistent_route():
    """
    Renders the 404.html template with a 404 status code.

    Returns:
        The rendered 404.html template with a 404 status code.
    """
    return render_template("404.html"), 404


@main.route("/favicon.ico")
def favicon():
    """
    Returns the favicon.ico file.

    Returns:
        The favicon.ico file.
    """
    return send_from_directory(
        os.path.join(main.root_path, "app\static"),
        "favicon.ico",
        mimetype="image/vnd.microsoft.icon",
    )

app/main/templates/503.html
{% extends "base.html" %}

{% block content %}
<section class="landing">
    <div class="content">
        <h1 class="text-primary text-center">503 Service Unavailable
        </h1>
        <p class="lead">
            “{{ _("For a moment, nothing happened. Then, after a second or so, nothing continued to happen.") }}”
        </p>
        <div class="btn-container">
            <a id="lastPageLink" class="btn btn-primary-outline not-found-back" href="javascript:goBack()">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="lucide lucide-move-left">
                  <path d="M6 8L2 12L6 16" />
                  <path d="M2 12H22" />
                </svg>
                {{ _("Go Back") }}
              </a>
        </div>
    </div>
</section>
{% endblock %}

app/main/templates/about.html
{% extends "base.html" %}

{% block styles %}
<link rel="stylesheet" type="text/css"
    href="{{ url_for('static', filename='css/about.css') }}">
{% endblock %}


{% block content %}
<section class="about wrapper">
    <div class="about-card">
        <div class="image-container">
            <img src="{{ url_for('static', filename='img/God2.webp') }}" alt="Image Description">
        </div>
        <div class="content">
            <div class="title">
                <h1>About</h1>
        <div class="spacer"></div>
        </div>
            <div class="title">
                <h3>“In the beginning this app was created. This has made a lot of people very angry and has been widely regarded as a bad move.”</h3>
            </div>
            <div class="spacer"></div>
            <div class="about-app-info">

                <h1>Share The Experience</h1>
                <p>
                    Life can be lonely when traveling. “The Hitchhikers Guide to Earth” gives you the opportunity to meet fellow travelers.
                    See beautiful and historic attractions. Add them to your wishlist and mark them as visited. Follow and compete with other travelers. Meet new friends or compete with existing ones. 
                    The application has something for everyone.  

                </p>
            </div>
            <div class="spacer"></div>
            <div class="about-app-info">

                <h1>Meet the Team</h1>
                <p>
                    Arctic Sprint Solutions AS is a fictional Norwegian Company created by students at UiT Norges Arktiske Universitet during the spring of 2024. The company develops software solutions for small to medium sized clients in the tourist industry. Being big fans of Douglas Adams book series “The Hitchhikers Guide to the Galaxy” and passionate about travelling, the group came together when a client contacted them in search for a new platform. The company has its headquarters in Tromso, Norway, but also has branches in northern and western Norway, as well as an international branch in New York City, USA. 
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

app/main/templates/change_language.html
{% extends "base.html" %}

{% block content %}
<div class="babel-fish">
	<h1>{{ _("Change Babel Fish") }}</h1>
	<div class="form-wrapper">
		<img src="{{ url_for('static', filename='img/babelfish.gif') }}" alt="">
		<form method="POST" action="{{ url_for('main.language') }}">
			<fieldset>
				<legend>{{ _("Change babelfish settings:") }}</legend>
				{% set default_language = session.get('language') or 'en' %}
				{% for lang in config.LANGUAGES %}
				<div class="form-control">
					<input type="radio" value="{{ lang }}" id="{{ lang }}"
						value="{{ lang }}" name="languages" {% if default_language==lang %}
						checked {% endif %}>
					<label for="{{ lang }}"> <img
							src="{{ url_for('static', filename='img/flags/%s.svg' % lang) }}"
							alt=""> {{ config.LANGUAGES.get(lang) }}</label>
				</div>
				{% endfor %}
			</fieldset>
			<input type="submit" value="{{ _(" Change Language") }}" name="languages"
				class="btn btn-primary btn-small">
		</form>
	</div>
</div>
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}

{% block content %}
<section class="landing">
    <div class="content">
        <h1 class="text-primary text-center">The Hitchhiker's Guide to Earth
        </h1>
        <p class="lead">
            “{{ _("The answer to the ultimate question of <span>cities</span>, <span>attractions</span> and <span>tourists</span> is… 42") }}”
        </p>
        <div class="btn-container">
            <a href="{{ url_for('auth.login') }}"
                class="btn btn-primary-outline">{{ _("Start Your Journey") }}</a>
        </div>
    </div>
</section>
{% endblock %}12